id: P4BA4DF94
initial_creation_type: input
source_metadata:
  title: Atiśa Dīpaṃkara Series
  language: nl
  description: Atiśa Dīpaṃkara Śrījñāna (982–1054), known as Jowo Jé Palden Atisha
    (jo bo rje dpal ldan a ti sha) in Tibetan, was a great Indian master and scholar.
    He spent the last ten years of his life in Tibet, teaching and translating texts,
    and was instrumental in reinvigorating Buddhism there after a period of persecution
    and decline.
  volume:
    29921e3b44c7424e84c7acf4632dcb65:
      title: Heart Treasure for the Warriors Who Long for Liberation
      parent: Advice
    7f78962ef9f94e4892aa519fb1552adc:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    0220aba560ba4de9935ba12d81003784:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Guru Yoga
    e35073b6f8e7451d93959a41bcf342e2:
      title: The Bodhisattva’s Garland of Jewels
      parent: Mind Training
    4ac42d10a02f4a6288d8fb4545032a45:
      title: An Extremely Concise Praise of the Twenty-One Tārās
      parent: Praise
    2e383f8925864549848a152365c0298a:
      title: Light Offering Prayer
      parent: Prayers
    55fa2b00c0f24e2aab1d65ca09ce91c8:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    b5a174db9e8b42beba37db3f14deebc7:
      title: Prayer to Ārya Tārā
      parent: Prayers
    c0f9b815810d4556976c62a4b97c20d6:
      title: Short Prayer to Atiśa
      parent: Prayers
created_at: '2022-03-01T02:10:55.973597'
last_modified_at: '2022-03-01T02:10:55.973600'
